language: go
go:
  - 1.14.1
install: true

script:
  - go test -cover ./... -coverprofile=coverage.txt -covermode=atomic

# push results to CodeCov
after_success:
  - bash <(curl -s https://codecov.io/bash)